config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  namespace :admin do
    resources :daily_habits
    resources :habits
    resources :habit_types
    resources :reminders
    resources :users

    root to: 'users#index'
  end
  devise_for :users
  telegram_webhook TelegramWebhooksController
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  root 'home#index'
  get 'todays_reminders_and_habits', to: 'home#todays_reminders_and_habits'
  get 'list_all_habits', to: 'home#list_all_habits'
  get 'calendar', to: 'home#calendar'
  get 'new_reminder_or_habit', to: 'home#new_reminder_or_habit'
  get '/service_worker.js' => 'service_worker#service_worker'
  get '/manifest.json' => 'service_worker#manifest'
  resources :habit_types
  resources :habits
  resources :users, only: %i[edit update]
  resources :reminders do
    member do
      patch :mark_done
    end
  end
  resources :daily_habits do
    member do
      patch :mark_done
    end
  end
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  include EmojisHelper
  belongs_to :user

  validates :title, presence: true
  validates :due_date, presence: true
  validates :user, presence: true
  validates :done, inclusion: { in: [true, false] }
  validate :due_date_cannot_be_in_the_past

  scope :upcoming, lambda { |days = 15|
                     where('due_date >= ?', Time.zone.now).where('due_date <= ?', Time.zone.now + days.days).where(done: false)
                   }
  scope :due_today, lambda {
                      where(due_date: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).where(done: false)
                    }

  after_create :schedule_notification

  def days_until_due
    (due_date.to_date - Date.today).to_i
  end

  def telegram_notification
    if days_until_due >= 1
      I18n.t('telegram.reminders.notification', title:, days_until_due:) + emoji(:clock, 3)
    else
      I18n.t('telegram.reminders.notification_today', title:) + emoji(:warning, 3)
    end
  end

  private

  def schedule_notification
    ReminderNotificationJob.set(wait_until: due_date - 2.hours).perform_later(self)
  end

  def due_date_cannot_be_in_the_past
    errors.add(:due_date, "can't be in the past") if due_date.present? && due_date < Time.zone.now
  end
end

app/controllers/admin/reminders_controller.rb
module Admin
  class RemindersController < Admin::ApplicationController
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: %i[show edit update destroy mark_done]

  def new
    @reminder = Reminder.new
  end

  def create
    @reminder = current_user.reminders.new(reminder_params)
    if @reminder.save!
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to root_path }
      end
    else
      render :new
    end
  end

  def mark_done
    return unless @reminder.update(done: true)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_path }
    end
  end

  private

  def set_reminder
    @reminder = Reminder.find(params[:id])
  end

  def reminder_params
    params.require(:reminder).permit(:title, :name, :due_date, :description)
  end
end

app/views/reminders/_form.html.erb
<div class="mt-4">
  <div class="row ">
    <div class="col-md-12">
      <div class="card shadow-sm">
        <div class="card-header bg-success text-white">
          <h5 class="mb-0">Nuevo Recordatorio</h3>
        </div>
        <div class="card-body">
          <%= simple_form_for reminder, data: { turbo: true } do |f| %>
            <div class="row d-flex align-items-center">
                <div class="form-inputs">
                  <%= f.input :title, label: false, placeholder: 'Titulo' %>
                  <%= f.input :due_date, as: :datetime, label: false, order: [:day, :month, :year, :hour, :minute] %>
                </div>
            <div class="orm-group d-flex justify-content-end">
              <%= f.button :submit, 'Remind Me', class: 'btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/reminders/_no_reminders.html.erb
<div class="card-body text-center">
  <i class="fas fa-check-circle text-success" style="font-size: 2rem;"></i>
  <p class="mt-3">Hoy no hay nada para recordar!</p>
</div>

app/views/reminders/_reminder.html.erb
<li id="<%= dom_id reminder %>"class="list-group-item d-flex justify-content-between align-items-center">
  <div class="col">
    <%= reminder.title %>
  </div>
  <div class="col">
    <%= reminder.due_date.strftime("%d/%m/%y %H:%M") %>
  </div>
  <% if reminder.due_date.past? %>
    <div class="col-auto d-flex justify-content-between">
      <% if reminder.done %>
        <i class="fas fa-check"></i>
      <% else %>
        <i class="fas fa-times"></i>
      <% end %>
    </div>
  <% else %>
    <div class="col-auto d-flex justify-content-between">
      <%= button_to mark_done_reminder_path(reminder), data: { turbo_frame: "daily_habits_list" }, method: :patch, class: 'btn btn-outline-primary rounded-circle' do %>
        <i class="fas fa-check"></i>
      <% end %>
    </div>
  <% end %>
</li>

app/views/reminders/_reminders_list.html.erb
<%= turbo_frame_tag "reminders_list" do %>
  <% if reminders.empty? %>
    <%= render partial: 'reminders/no_reminders'%>
  <% else %>
    <ul class="list-group list-group-flush">
      <%= render partial:'reminders/reminder', collection: reminders %>
    </ul>
  <% end %>
<% end%>

app/views/reminders/create.turbo_stream.erb
<%= turbo_stream.replace "reminders_list", partial: "reminders/reminders_list", locals: { reminders: current_user.reminders.upcoming } %>

app/views/reminders/mark_done.turbo_stream.erb
<%= turbo_stream.replace "reminders_list", partial: "reminders/reminders_list", locals: { reminders: current_user.reminders.upcoming } %>

app/views/reminders/new.html.erb
<div id="new-remidner">
  <%= render 'form', reminder: @reminder%>
</div>