config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  namespace :admin do
    resources :daily_habits
    resources :habits
    resources :habit_types
    resources :reminders
    resources :users

    root to: 'users#index'
  end
  devise_for :users
  telegram_webhook TelegramWebhooksController
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  root 'home#index'
  get 'todays_reminders_and_habits', to: 'home#todays_reminders_and_habits'
  get 'list_all_habits', to: 'home#list_all_habits'
  get 'calendar', to: 'home#calendar'
  get 'new_reminder_or_habit', to: 'home#new_reminder_or_habit'
  get '/service_worker.js' => 'service_worker#service_worker'
  get '/manifest.json' => 'service_worker#manifest'
  resources :habit_types
  resources :habits
  resources :users, only: %i[edit update]
  resources :reminders do
    member do
      patch :mark_done
    end
  end
  resources :daily_habits do
    member do
      patch :mark_done
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    return unless user_signed_in?

    DailyHabitService.new(current_user).create_daily_habits
    @daily_habits = current_user.daily_habits_for_today
    @reminders = current_user.reminders.upcoming
  end

  def todays_reminders_and_habits
    @daily_habits = current_user.daily_habits_for_today
    @reminders = current_user.reminders.upcoming
    render turbo_stream: turbo_stream.replace('content_frame', partial: 'daily_actions',
                                                               locals: { daily_habits: @daily_habits,
                                                                         reminders: @reminders })
  end

  def list_all_habits
    @habits = current_user.habits
    @daily_habit_chart = DailyHabitGraphService.new(@current_user).calculate
    render turbo_stream: turbo_stream.replace('content_frame', partial: 'habits_actions',
                                                               locals: { habits: @habits })
  end

  def new_reminder_or_habit
    @habits = current_user.habits
    render turbo_stream: turbo_stream.replace('content_frame', partial: 'new_reminder_or_habit')
  end

  def calendar # rubocop:disable Metrics/AbcSize
    @selected_date = (params[:date].present? ? Date.parse(params[:date]) : Date.today).all_day
    @daily_habits = current_user.daily_habits.where(created_at: @selected_date)
    @reminders = current_user.reminders.where(due_date: @selected_date)
    @daily_rating = current_user.daily_ratings.find_by(rated_on: @selected_date)
    render turbo_stream: turbo_stream.replace('content_frame', partial: 'calendar')
  end
end

app/views/home/_calendar.html.erb
<%= turbo_frame_tag "content_frame" do %>
  <div class="container mt-4 mb-4">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-10 col-lg-8">
        <%= form_tag(calendar_path, method: :get, id: "date-select-form", class: "row align-items-center") do %>
          <div class="col-8 col-md-8">
            <%= date_field_tag :date, @selected_date, class: "form-control" %>
          </div>
          <div class="col-3 col-md-2">
            <%= submit_tag "Seleccionar", class: "btn btn-success btn-block"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= render partial: 'daily_rating', locals: { daily_rating: @daily_rating }%>
  <%= render partial: 'daily_actions', locals: { reminders: @reminders, daily_habits: @daily_habits } %>
<% end %>

app/views/home/_daily_actions.html.erb
<div class="card mb-4 shadow-sm"> 
  <div class="card-header bg-success text-white">
    <h5 class="mb-0">Recordatorios</h5> 
  </div>
  <div class="card-body">
    <ul class="list-group list-group-flush">
      <%= render partial: 'reminders/reminders_list', locals: { reminders: reminders } %>
    </ul>
  </div>
</div>
<div class="card mb-4 shadow-sm"> 
  <div class="card-header bg-success text-white">
    <h5 class="mb-0">Habitos para hoy</h5> 
  </div>
  <div class="card-body">
    <ul class="list-group list-group-flush">
      <%= render partial: 'daily_habits/daily_habits_list', locals: { daily_habits: daily_habits } %>
    </ul>
  </div>
</div>

app/views/home/_daily_rating.html.erb
<div class="card mb-4 shadow-sm">
  <div class="card-header bg-success text-white">
    <h5 class="mb-0">Resultado del Día</h5>
  </div>
  <div class="card-body text-center">
    <% if @daily_rating.present? %>
      <p class="card-text" style="font-size: 2rem;""><%= rating_emoji(@daily_rating.rating) %> (<%= @daily_rating.rating %>)</p>
    <% else %>
      <p class="card-text">No hay resultado registrado</p>
    <% end %>
  </div>

</div>

app/views/home/_habits_actions.html.erb
<%= turbo_frame_tag "content_frame" do %>
  <div class="card mb-4 shadow-sm"> 
    <div class="card-header bg-success text-white">
      <h5 class="mb-0">Estadisticas</h5> 
    </div>
    <div class="card-body">
      <%= render partial: 'habits/habit_stats', locals: { habits: @habits} %>
    </div>
  </div>
  <div class="card mb-4 shadow-sm"> 
    <div class="card-header bg-success text-white">
      <h5 class="mb-0">Grafica</h5> 
    </div>
    <div class="card-body">
      <%= render partial: 'daily_habits/daily_habits_chart', locals: { daily_habit_chart: @daily_habit_chart} %>
    </div>
  </div>
<% end %>

app/views/home/_new_reminder_or_habit.html.erb
<%= turbo_frame_tag "content_frame" do %>
  <%= render partial: 'reminders/form', locals: { reminder: Reminder.new} %>
  <%= render partial: 'habits/form', locals: { habit: Habit.new} %>
  <div class="mt-4">
      <div class="card mb-4 shadow-sm"> 
        <div class="card-header bg-success text-white">
          <h5 class="mb-0">Habitos</h5> 
        </div>
        <div class="card-body">
          <%= render partial: 'habits/habit_list', locals: { habits: @habits} %>
        </div>
      </div>
    </div>
<% end %>

app/views/home/index.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-6"> <!-- Adjust the column sizes as needed -->
      <div class="d-flex justify-content-center mb-4">
        <div class="btn-group" role="group" aria-label="View options">
          <%= link_to "Hoy", root_path, class: "btn btn-success tab-button", data: { turbo_frame: "content_frame" } %>
          <%= link_to "Calendario", calendar_path, class: "btn btn-success tab-button", data: { turbo_frame: "content_frame" } %>
          <%= link_to "Stats", list_all_habits_path, class: "btn btn-success tab-button", data: { turbo_frame: "content_frame" } %>
          <%= link_to "Nuevos", new_reminder_or_habit_path, class: "btn btn-success tab-button", data: { turbo_frame: "content_frame" } %>
        </div>
      </div>
      <%= turbo_frame_tag "content_frame" do %>
        <%= render partial: 'daily_actions', locals: { reminders: @reminders, daily_habits: @daily_habits } %>
      <% end %>
    </div>
  </div>
</div>