config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  namespace :admin do
    resources :daily_habits
    resources :habits
    resources :habit_types
    resources :reminders
    resources :users

    root to: 'users#index'
  end
  devise_for :users
  telegram_webhook TelegramWebhooksController
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  root 'home#index'
  get 'todays_reminders_and_habits', to: 'home#todays_reminders_and_habits'
  get 'list_all_habits', to: 'home#list_all_habits'
  get 'calendar', to: 'home#calendar'
  get 'new_reminder_or_habit', to: 'home#new_reminder_or_habit'
  get '/service_worker.js' => 'service_worker#service_worker'
  get '/manifest.json' => 'service_worker#manifest'
  resources :habit_types
  resources :habits
  resources :users, only: %i[edit update]
  resources :reminders do
    member do
      patch :mark_done
    end
  end
  resources :daily_habits do
    member do
      patch :mark_done
    end
  end
end

app/models/daily_habit.rb
class DailyHabit < ApplicationRecord
  belongs_to :habit
  belongs_to :user

  validates :habit, presence: true
  validates :user, presence: true
  validate :habit_not_already_logged_today
  validate :habit_is_active_today

  scope :not_done, -> { where(done: false) }

  def name
    habit.name
  end

  private

  def habit_is_active_today
    date = created_at ? created_at.to_date : Date.current
    return if habit.active_days.include?((date.wday.zero? ? 7 : date.wday).to_s)

    errors.add(:habit_id, 'is not active today')
  end

  def habit_not_already_logged_today
    time_frame = created_at ? created_at.beginning_of_day..created_at.end_of_day : Time.zone.now.beginning_of_day..Time.zone.now.end_of_day
    is_logged_today = DailyHabit.where(user_id:, habit_id:)
                                .where('created_at >= ? AND created_at <= ?', time_frame.begin, time_frame.end)
                                .where.not(id:)
                                .exists?
    errors.add(:habit_id, 'has already been logged for today') if is_logged_today
  end
end

app/controllers/admin/daily_habits_controller.rb
module Admin
  class DailyHabitsController < Admin::ApplicationController
  end
end

app/controllers/daily_habits_controller.rb
class DailyHabitsController < ApplicationController
  before_action :set_daily_habit, only: [:mark_done]

  def mark_done
    if @daily_habit.update(done: true)
      @daily_habits = current_user.daily_habits_for_today
      UpdateDailyHabitJob.perform_later(daily_habit: @daily_habit, user: current_user)
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to root_path }
      end
    else
      redirect_to root_path, alert: 'Unable to update the habit.'
    end
  end

  private

  def set_daily_habit
    @daily_habit = DailyHabit.find(params[:id])
  end
end

app/views/daily_habits/_daily_habit.html.erb
<li id="<%= dom_id daily_habit %>" class="list-group-item d-flex justify-content-between align-items-center">
  <div class='col-3'>
    <%= daily_habit.habit.name %>
  </div>
  <div class='col-3'>
    <em><%= daily_habit.habit.habit_type.name %></em>
  </div>
  <% if daily_habit.created_at.to_date == Date.today %>
    <div class='col-3'>
      <strong><%= daily_habit.habit.streak %> dias de racha!</strong>
      <% if daily_habit.habit.streak > 5 %>
        🔥
      <% end %>
    </div>
    <%= button_to mark_done_daily_habit_path(daily_habit), data: { turbo_frame: "daily_habits_list" }, method: :patch, class: 'btn btn-outline-success rounded-circle' do %>
      <i class="fas fa-check"></i>
    <% end %>
  <% else %>
    <div class='col-3'>
      <strong><%= daily_habit.created_at.to_date %></strong>
    </div>
    <% if daily_habit.done %>
      <i class="fas fa-check"></i>
    <% else %>
      <i class="fas fa-times"></i>
    <% end %>

  <% end %>
</li>

app/views/daily_habits/_daily_habits_chart.html.erb
<%= column_chart daily_habit_chart, stacked: true, title: t('graphs.daily_habit_per_day.title'),
  dataset: {
      barPercentage: 0.5,
      barThickness: 10,
    },
  library: {
    title: {
      style: { color: "#333", fontSize: "20px", fontWeight: "bold" }
    },
    yAxis: {
      allowDecimals: false,
      title: {
        text: 'Habits Count',
        style: { color: "#333", fontSize: "14px" }
      }
    },
    xAxis: {
      title: {
        style: { color: "#333", fontSize: "14px" }
      },
      labels: {
        style: { color: "#333", fontSize: "12px" }
      }
    },
    legend: {
      layout: 'vertical',
      align: 'right',
      verticalAlign: 'top',
      x: -40,
      y: 80,
      floating: true,
      borderWidth: 1,
      backgroundColor: '#FFFFFF',
      shadow: true,
      itemStyle: {
        color: '#333',
        fontSize: '12px'
      }
    },
    tooltip: {
      backgroundColor: 'rgba(0, 0, 0, 0.85)',
      style: {
        color: '#FFF'
      }
    },
    plotOptions: {
      column: {
        stacking: 'normal',
        dataLabels: {
          enabled: true,
          style: {
            fontSize: '12px',
            fontWeight: 'bold',
            color: 'white'
          }
        }
      }
    }
  }
%>

app/views/daily_habits/_daily_habits_list.html.erb
<%= turbo_frame_tag "daily_habits_list" do %>
  <% if daily_habits.empty? %>
    <%= render partial: 'daily_habits/no_more_habits'%>
  <% else %>
    <ul class="list-group list-group-flush">
      <%= render partial:'daily_habits/daily_habit', collection: daily_habits %>
    </ul>
  <% end %>
<% end%>

app/views/daily_habits/_no_more_habits.html.erb
<div class="card-body text-center">
  <i class="fas fa-check-circle text-success" style="font-size: 2rem;"></i>
  <p class="mt-3">All done for today! You're definitely staying <strong>On Track</strong>!</p>
</div>

app/views/daily_habits/mark_done.turbo_stream.erb
<%= turbo_stream.replace "daily_habits_list", partial: "daily_habits/daily_habits_list", locals: { daily_habits: @daily_habits } %>