config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  namespace :admin do
    resources :daily_habits
    resources :habits
    resources :habit_types
    resources :reminders
    resources :users

    root to: 'users#index'
  end
  devise_for :users
  telegram_webhook TelegramWebhooksController
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  root 'home#index'
  get 'todays_reminders_and_habits', to: 'home#todays_reminders_and_habits'
  get 'list_all_habits', to: 'home#list_all_habits'
  get 'calendar', to: 'home#calendar'
  get 'new_reminder_or_habit', to: 'home#new_reminder_or_habit'
  get '/service_worker.js' => 'service_worker#service_worker'
  get '/manifest.json' => 'service_worker#manifest'
  resources :habit_types
  resources :habits
  resources :users, only: %i[edit update]
  resources :reminders do
    member do
      patch :mark_done
    end
  end
  resources :daily_habits do
    member do
      patch :mark_done
    end
  end
end

app/models/habit.rb
# frozen_string_literal: true

class Habit < ApplicationRecord
  belongs_to :habit_type
  belongs_to :user
  has_many :daily_habits, dependent: :destroy

  before_create :set_disabled_to_false
  after_create :create_daily_habits_for_user

  scope :active, lambda {
    where('active_days @> ARRAY[?]::varchar[]', [(Date.current.wday.zero? ? 7 : Date.current.wday).to_s])
  }

  # Method to calculate the streak
  def streak
    daily_habits.where(done: true).where('created_at >= ? AND created_at <= ?', streak_start_date,
                                         Date.current.end_of_day).count
  end

  def accomplishment_percentage(accomplishment_days = 30)
    start_date = accomplishment_days.days.ago.beginning_of_day
    end_date = Date.current.end_of_day
    recent_daily_habits = daily_habits.where(created_at: start_date..end_date)
    return 0 if recent_daily_habits.empty?

    (recent_daily_habits.where(done: true).count.to_f / recent_daily_habits.count) * 100
  end

  private

  def streak_start_date
    last_incomplete_day = daily_habits.where(done: false)
                                      .where('created_at < ?', Date.current.beginning_of_day)
                                      .order(created_at: :desc)
                                      .first
    last_incomplete_day ? last_incomplete_day.created_at.to_date + 1.day : created_at.to_date
  end

  def create_daily_habits_for_user
    return unless active_days.include?((Date.current.wday.zero? ? 7 : Date.current.wday).to_s)

    daily_habits.create!(user:,
                         done: false)
  end

  def set_disabled_to_false
    self.disabled = false
  end
end

app/models/habit_type.rb
# frozen_string_literal: true

class HabitType < ApplicationRecord
  has_many :habits
end

app/controllers/admin/habits_controller.rb
module Admin
  class HabitsController < Admin::ApplicationController
  end
end

app/controllers/habits_controller.rb
# frozen_string_literal: true

class HabitsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_habit, only: %i[show edit update destroy]

  def new
    @habit = Habit.new
  end

  def create
    @habit = current_user.habits.new(habit_params)
    if @habit.save!
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to root_path }
      end
    else
      render :new
    end
  end

  def update
    if @habit.update(habit_params)
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to root_path }
      end
    else
      render :edit
    end
  end

  def destroy
    return unless @habit.destroy!

    @habits = current_user.habits.page(params[:page]).per(10)
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@habit) }
      format.html         { redirect_to root_path }
    end
  end

  private

  def habit_params
    params.require(:habit).permit(:name, :description, :habit_type_id, :disable, active_days: [])
  end

  def set_habit
    @habit = Habit.find(params[:id])
  end
end

app/helpers/habits_helper.rb
module HabitsHelper
  def on_track?(accomplishment_percentage, user)
    if accomplishment_percentage >= user.on_track_percentage * 100
      'On track'
    else
      'Off track'
    end
  end
end

app/views/habits/_form.html.erb
<div class="mt-4">
  <div class="row">
    <div class="col-md-12">
      <div class="card shadow-sm">
        <div class="card-header bg-success text-white">
          <h5 class="mb-0">Nuevo Habito</h5>
        </div>
        <div class="card-body">
          <%= simple_form_for habit, data: { turbo: true } do |f| %>
            <!-- Use Bootstrap's mb-* classes to add bottom margin for spacing -->
            <div class="form-group mb-3"> <!-- Add spacing between form groups -->
              <%= f.input :name, label: false, input_html: { class: 'form-control', placeholder: 'Nombre' } %>
            </div>
            <div class="form-group mb-3"> <!-- Add spacing between form groups -->
              <%= f.association :habit_type, label: false, include_blank: false, input_html: { class: 'form-select' } %>
            </div>
            <div class="form-group mb-3"> <!-- Adjust spacing for the day checkboxes -->
              <% Date::DAYNAMES.rotate(1).each_with_index do |day, index| %>
                <div class="form-check form-check-inline"> <!-- Use inline checks for days, ensuring they are spaced nicely -->
                  <%= f.check_box :active_days, { id: "day_#{index}", multiple: true, class: 'd-none' }, (index+1), nil %>
                  <label for="day_<%= index %>" class="day-btn"><%= day[0] %></label>
                </div>
              <% end %>
            </div>
            <div class="form-group d-flex justify-content-end">
              <%= f.button :submit, class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/habits/_habit.html.erb
<%= turbo_frame_tag habit do %>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <div class="col">
        <%= habit.name %>
      </div>
      <div class="col-5">
        <div class="active-days">
            <% Date::DAYNAMES.rotate(1).each_with_index do |day, index| %>
              <% if habit.active_days.include?((index+1).to_s) %>
                <span class="day-btn active"><%= day[0] %></span>
              <% end %>
            <% end %>
          </div>
      </div>
      <div class="col d-flex justify-content-between">
        <%= link_to 'Edit', edit_habit_path(habit), data: { turbo_frame: "habit_#{habit.id}" }, class: "btn btn-danger ms-2" %>
        <%= button_to "Delete", habit, method: :delete, data: { confirm: "Are you sure you want to delete this habit?" }, class: "btn btn-danger ms-2" %>
      </div>
    </li>
<% end %>

app/views/habits/_habit_list.html.erb
<%= turbo_frame_tag "habit_list" do %>  
  <% if habits.empty? %>
      <p class="card-text">You have no habits yet. Create one now!</p>
  <% else%>
    <ul id='habit_list' class="list-group list-group-flush">
        <%= render partial: "habits/habit", collection: habits %>
    </ul>
  <%end%>
<% end %>

app/views/habits/_habit_stats.html.erb
<%= turbo_frame_tag "habit_stats" do %>  
  <% if habits.empty? %>
      <p class="card-text">You have no habits yet. Create one now!</p>
  <% else%>
    <ul id='habit_list' class="list-group list-group-flush">
      <% habits.each do |habit| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="col-4">
            <%= habit.name %>
          </div>
          <div class="col-4">
            <strong><%= habit.streak %> dias de racha!</strong>
            <% if habit.streak > 5 %>
              🔥
            <% end %>
          </div>
          <div class="col-4">
            <%= on_track?(habit.accomplishment_percentage, current_user) =%>
            (<%= number_with_precision(habit.accomplishment_percentage, precision: 0) %>%)
          <div>
        </li>
      <% end %>
    </ul>
  <%end%>
<% end %>

app/views/habits/create.turbo_stream.erb
<%= turbo_stream.replace "habit_list", partial: "habits/habit_list", locals: { habits: current_user.habits.page.per(20) } %>
<%= turbo_stream.replace "daily_habits_list", partial: "daily_habits/daily_habits_list", locals: { daily_habits: current_user.daily_habits_for_today } %>

app/views/habits/edit.html.erb
<%= turbo_frame_tag @habit do %>
  <%= simple_form_for @habit, data: { turbo: true } do |form| %>
    <div class="list-group-item d-flex justify-content-between align-items-center">
      <div class="row d-flex justify-content-between">
        <div class="col">
          <%= form.input :name, label: false, input_html: { class: 'form-control' } %>
        </div>
        <div class="col-auto">
          <% Date::DAYNAMES.rotate(1).each_with_index do |day, day_index| %>
            <% checkbox_id = "habit_#{day.downcase}_#{day_index}" %>
            <%= form.check_box :active_days, { id: checkbox_id, multiple: true, class: 'd-none' }, (day_index+1).to_s, nil %>
            <label for="<%= checkbox_id %>" class="day-btn"><%= day[0] %></label>
          <% end %>
        </div>
        <div class="col-auto align-self-start">
          <%= form.submit 'Save', class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/habits/new.html.erb
<div id="new-habit">
  <%= render 'form', habit: @habit%>
</div>

app/views/habits/update.turbo_stream.erb
<%= turbo_stream.replace @habit do %>
  <%= render partial: "habit", locals: { habit: @habit } %>
<% end %>